# Generated by Django 4.2.2 on 2023-07-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicken_farm', '0003_dailyreport_total_remaining_eggs'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='productivity',
            field=models.FloatField(default=0, verbose_name='productivity'),
        ),
    ]
