# Generated by Django 4.2.2 on 2023-07-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicken_farm', '0004_dailyreport_productivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='productivity',
            field=models.FloatField(blank=True, null=True, verbose_name='productivity'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='total_remaining_eggs',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='total remaining eggs'),
        ),
    ]
