# Generated by Django 4.2.2 on 2023-08-06 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chicken_farm', '0005_alter_dailyreport_productivity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmDailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('laid_eggs', models.PositiveIntegerField(default=0, verbose_name='laid eggs')),
                ('broken_eggs', models.PositiveIntegerField(default=0, verbose_name='broken eggs')),
                ('dead_chickens', models.PositiveIntegerField(default=0, verbose_name='dead chickens')),
                ('total_remaining_eggs', models.PositiveIntegerField(blank=True, null=True, verbose_name='total remaining eggs')),
                ('remaining_chickens', models.PositiveIntegerField(blank=True, null=True, verbose_name='remaining chickens')),
                ('productivity', models.FloatField(blank=True, null=True, verbose_name='productivity')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='date')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Reported by')),
            ],
            options={
                'verbose_name': 'daily report',
                'verbose_name_plural': 'daily reports',
            },
        ),
        migrations.CreateModel(
            name='FarmIncomeDebtPayback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('card_payment', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Card money')),
                ('cash_payment', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cash money')),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='paid at')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Reported by')),
            ],
            options={
                'verbose_name': 'income debt payback',
                'verbose_name_plural': 'income debt paybacks',
            },
        ),
        migrations.CreateModel(
            name='FarmSalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('sold_eggs', models.PositiveIntegerField(default=0, help_text='sold eggs in boxes', verbose_name='sold eggs')),
                ('price_per_box', models.PositiveIntegerField(default=0, verbose_name='price per box')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='comments')),
                ('card_payment', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Card money')),
                ('cash_payment', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cash money')),
                ('debt_payment', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Debt money')),
                ('sold_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='sold at')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Reported by')),
            ],
            options={
                'verbose_name': 'sales report',
                'verbose_name_plural': 'sales reports',
            },
        ),
        migrations.DeleteModel(
            name='DailyReport',
        ),
        migrations.AddField(
            model_name='farmincomedebtpayback',
            name='sales_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_paybacks', to='chicken_farm.farmsalesreport', verbose_name='Sales report'),
        ),
    ]
