# Generated by Django 4.2.2 on 2023-08-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicken_farm', '0006_farmdailyreport_farmincomedebtpayback_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmincomedebtpayback',
            name='card_payment',
        ),
        migrations.RemoveField(
            model_name='farmincomedebtpayback',
            name='cash_payment',
        ),
        migrations.AddField(
            model_name='farmincomedebtpayback',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Amount'),
        ),
        migrations.AddField(
            model_name='farmincomedebtpayback',
            name='payment_method',
            field=models.CharField(choices=[('CARD', 'Card'), ('CASH', 'Cash')], default='CARD', max_length=15, verbose_name='Payment method'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='farmsalesreport',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
    ]
