# Generated by Django 4.2.2 on 2023-08-06 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chicken_farm', '0007_remove_farmincomedebtpayback_card_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('card_payment', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Card money')),
                ('cash_payment', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cash money')),
                ('debt_payment', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Debt money')),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='expenses', verbose_name='image')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='date')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Reported by')),
            ],
            options={
                'verbose_name': 'expense',
                'verbose_name_plural': 'expenses',
            },
        ),
        migrations.CreateModel(
            name='FarmExpenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
            options={
                'verbose_name': 'expense type',
                'verbose_name_plural': 'expense types',
            },
        ),
        migrations.CreateModel(
            name='FarmOutgoingsDebtPayback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('card_payment', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Card money')),
                ('cash_payment', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cash money')),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='paid at')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_paybacks', to='chicken_farm.farmexpense', verbose_name='expense')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Reported by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='farmexpense',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='chicken_farm.farmexpensetype', verbose_name='type'),
        ),
    ]
