# Generated by Django 4.2.2 on 2023-08-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicken_farm', '0008_farmexpense_farmexpensetype_farmoutgoingsdebtpayback_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmoutgoingsdebtpayback',
            options={'verbose_name': 'Outgoings debt payback', 'verbose_name_plural': 'Outgoings debt paybacks'},
        ),
        migrations.RemoveField(
            model_name='farmoutgoingsdebtpayback',
            name='card_payment',
        ),
        migrations.RemoveField(
            model_name='farmoutgoingsdebtpayback',
            name='cash_payment',
        ),
        migrations.AddField(
            model_name='farmoutgoingsdebtpayback',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Money amount'),
        ),
        migrations.AddField(
            model_name='farmoutgoingsdebtpayback',
            name='payment_method',
            field=models.CharField(choices=[('CARD', 'Card'), ('CASH', 'Cash')], default='CASH', max_length=15, verbose_name='Payment method'),
            preserve_default=False,
        ),
    ]
