# Generated by Django 4.2.2 on 2023-08-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicken_farm', '0010_farmdebtpayback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmexpense',
            name='item_amount',
            field=models.CharField(default='', max_length=127, verbose_name='item amount'),
            preserve_default=False,
        ),
    ]
