# Generated by Django 4.2.2 on 2023-08-20 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chicken_farm', '0011_farmexpense_item_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmsalesreport',
            old_name='sold_eggs',
            new_name='sold_egg_boxes',
        ),
    ]
