# Generated by Django 4.2.2 on 2023-08-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicken_farm', '0012_rename_sold_eggs_farmsalesreport_sold_egg_boxes'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmdailyreport',
            name='via_sales_report',
            field=models.BooleanField(default=False, verbose_name='via sales report'),
        ),
    ]
