# Generated by Django 4.2.2 on 2023-08-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicken_farm', '0014_alter_farmsalesreport_price_per_box_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmresource',
            name='chickens_count',
        ),
        migrations.RemoveField(
            model_name='farmresource',
            name='eggs_count',
        ),
        migrations.AddField(
            model_name='farmresource',
            name='current_chickens_count',
            field=models.PositiveIntegerField(default=0, verbose_name='current chickens count'),
        ),
        migrations.AddField(
            model_name='farmresource',
            name='current_eggs_count',
            field=models.PositiveIntegerField(default=0, verbose_name='current eggs count'),
        ),
        migrations.AddField(
            model_name='farmresource',
            name='initial_chickens_count',
            field=models.PositiveIntegerField(default=0, verbose_name='current chickens count'),
        ),
        migrations.AddField(
            model_name='farmresource',
            name='initial_eggs_count',
            field=models.PositiveIntegerField(default=0, verbose_name='current eggs count'),
        ),
    ]
