# Generated by Django 4.2.2 on 2023-08-30 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chicken_farm', '0018_farmexpense_comment_farmexpense_item_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmexpensetype',
            name='amount',
            field=models.FloatField(default=0, verbose_name='amount'),
        ),
        migrations.CreateModel(
            name='FarmFodderIngredientUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('amount', models.FloatField(verbose_name='amount')),
                ('remaining_amount', models.FloatField(verbose_name='remaining amount')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='date')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chicken_farm.farmexpensetype', verbose_name='ingredient')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Reported by')),
            ],
            options={
                'verbose_name': 'fodder ingredient usage',
                'verbose_name_plural': 'fodder ingredients usage',
            },
        ),
    ]
