# Generated by Django 4.2.2 on 2023-09-05 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicken_farm', '0019_farmexpensetype_amount_farmfodderingredientusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmfodderingredientusage',
            name='remaining_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='remaining amount'),
        ),
    ]
