# Generated by Django 4.2.2 on 2023-09-05 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicken_farm', '0021_rename_amount_farmexpensetype_remaining_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmexpensetype',
            name='remaining_amount',
            field=models.FloatField(default=0, verbose_name='remaining amount'),
        ),
    ]
