# Generated by Django 4.2.2 on 2023-09-15 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicken_farm', '0022_alter_farmexpensetype_remaining_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmdebtpayback',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Money amount'),
        ),
        migrations.AlterField(
            model_name='farmexpense',
            name='card_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Card money'),
        ),
        migrations.AlterField(
            model_name='farmexpense',
            name='cash_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Cash money'),
        ),
        migrations.AlterField(
            model_name='farmexpense',
            name='debt_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Debt money'),
        ),
        migrations.AlterField(
            model_name='farmsalesreport',
            name='card_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Card money'),
        ),
        migrations.AlterField(
            model_name='farmsalesreport',
            name='cash_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Cash money'),
        ),
        migrations.AlterField(
            model_name='farmsalesreport',
            name='debt_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Debt money'),
        ),
    ]
