# Generated by Django 4.2.2 on 2023-07-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0004_alter_orderitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='needed_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Needed quantity'),
        ),
    ]
