# Generated by Django 4.2.2 on 2023-07-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('cook', 'Cook'), ('provider', 'Provider'), ('farm_counter', 'Farm Counter')], default='admin', max_length=20),
        ),
    ]
